---
- name: Template to Create a User in Linux Machine.
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Create User
      user:
        name: "{{ item }}"
        state: present
        password: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits,punctuation') }}"
      with_items: "{{ username.split(',') }}"
