---

- name: Template to Create a User in Linux Machine.
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Create User
      user:
        name: "{{ username }}"
        state: present
