---
- name: Template to Create a User in Linux Machine.
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Create User
      user:
        name: "{{ item }}"
        state: present
        password: "{{ lookup('password', '/dev/null chars=ascii_lowercase,ascii_uppercase,digits,punctuation length=16') }}"
      with_items: "{{ username.split(',') }}"
