---

- name: Template to Delete a User in Linux Machine.
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Delete User
      user:
        name: "{{ username }}"
        state: absent
