---
- name: Template to Create a User in Linux Machine.
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Create User
      user:
        name: "{{ item }}"
        state: present
        password: "{{ user_password | password('sha512') }}"
      with_items: "{{ username.split(',') }}"
